#: import dp kivy.metrics.dp

<AudioRV>:
    orientation: 'vertical'
    RecycleView:
        id: rv
        viewclass: 'AudioFileView'
        RecycleGridLayout:
            cols: 1
            default_size_hint: (1, None)
            default_size: (None, dp(72))
            size_hint_y: None
            height: self.minimum_height
            spacing: dp(10)
            padding: [dp(12), dp(8), dp(12), dp(8)]

