name: Build A Signed APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
      # Used to cache dependencies with a timeout
      - name: Get Date
        id: get-date
        run: |
          echo "date=$(date -u '+%Y%m%d')" >> $GITHUB_ENV
        shell: bash

      - name: Cache Buildozer global directory
        uses: actions/cache@v4
        with:
          path: ~/.buildozer
          key: buildozer-global-${{ runner.os }}-${{ steps.get-date.outputs.date }}-${{ hashFiles('buildozer.spec') }}
          restore-keys: |
            buildozer-global-${{ runner.os }}-

      - name: Cache Buildozer directory in app
        uses: actions/cache@v4
        with:
          path: .buildozer
          key: ${{ runner.os }}-buildozer-${{ github.run_id }}-${{ hashFiles('buildozer.spec') }}
          restore-keys: |
            ${{ runner.os }}-buildozer-

      - name: Cache Android SDK
        uses: actions/cache@v4
        with:
          path: ~/.buildozer/android/platform/android-sdk
          key: ${{ runner.os }}-android-sdk-${{ steps.get-date.outputs.date }}
          restore-keys: |
            ${{ runner.os }}-android-sdk-

      - name: Cache Android NDK
        uses: actions/cache@v4
        with:
          path: ~/.buildozer/android/platform/android-ndk-r25b
          key: ${{ runner.os }}-android-ndk-${{ steps.get-date.outputs.date }}
          restore-keys: |
            ${{ runner.os }}-android-ndk-

      # Step 1: Decode Keystore from base64
      - name: Decode Keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > android.jks

      # Step 2: Build Release APK using Buildozer
      - name: Build Release APK
        uses: digreatbrian/buildozer-action@v2
        with:
          python-version: 3.11
          buildozer-cmd: buildozer -v android release

      
      # Step 3: Zipalign and Sign the APK
      - name: Zipalign and Sign APK
        run: |
          # 1. Find the unsigned release APK
          UNSIGNED_APK=$(find ./bin -name "*-release-unsigned.apk" | head -n 1)
          
          # 2. Get the latest build-tools path
          BUILD_TOOLS_PATH=$(ls -d ${ANDROID_SDK_ROOT}/build-tools/* | tail -1)
          
          # 3. Zipalign (MUST be done before apksigner)
          $BUILD_TOOLS_PATH/zipalign -v -p 4 "$UNSIGNED_APK" aligned-release.apk
          
          # 4. Sign with apksigner
          $BUILD_TOOLS_PATH/apksigner sign --ks android.jks \
            --ks-pass pass:"${{ secrets.KEYSTORE_PASSWORD }}" \
            --ks-key-alias "${{ secrets.KEY_ALIAS }}" \
            --key-pass pass:"${{ secrets.KEY_PASSWORD }}" \
            --out release-signed.apk aligned-release.apk

      # Step 4: Upload the final signed APK
      - name: Upload Signed APK
        uses: actions/upload-artifact@v4
        with:
          name: signed-release-apk
          path: release-signed.apk


     

      
